### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by bhhaskin** [arnaudjbernard/swap-copy-paste#2]
[Enter steps to reproduce below:]
1. try to use the plugin on the settings page.

**Atom Version**: 0.174.0
**System**: linux 3.13.0-24-generic
**Thrown From**: [swap-copy-paste](https://github.com/arnaudjbernard/swap-copy-paste) package, v0.1.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/bryan/.atom/packages/swap-copy-paste/lib/swap-copy-paste.coffee:11

TypeError: undefined is not a function
  at Object.module.exports.swap (/home/bryan/.atom/packages/swap-copy-paste/lib/swap-copy-paste.coffee:11:26)
  at atom-workspace.<anonymous> (/home/bryan/.atom/packages/swap-copy-paste/lib/swap-copy-paste.coffee:4:60)
  at atom-workspace.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)

```
### Commands

```
     -1:58.3 command-palette:toggle (atom-pane.pane.active)
     -1:56.4 core:confirm (atom-text-editor.editor.mini)
     -1:56.3 settings-view:open (atom-pane.pane.active)
     -0:07.6 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-seti-syntax.theme-seti-ui)
     -0:00.0 swap-copy-paste:swap (div.deprecation-cop.pane-item.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-color-highlight, v3.0.5
autoclose-html, v0.13.0
color-picker, v1.4.3
file-icons, v1.4.8
gist-it, v0.6.3
highlight-line, v0.9.3
highlight-selected, v0.7.0
html-id-class-snippets, v1.4.1
htmlhint, v0.4.0
linter, v0.10.0
linter-flake8, v1.2.0
linter-php, v0.0.11
minimap, v3.5.6
project-manager, v1.15.0
script, v2.16.0
seti-syntax, v0.2.1
seti-ui, v0.6.1
wordpress, v0.2.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by bhhaskin** [comment]
My guess it is an issue of trying to past to an area that is read only.
